"""Analyze the language sweep — produce summary table + correlation figure.

Reads:
    results/lang_sweep_logs/manifest.csv         (loss ratios)
    results/lang_sweep_logs/discriminability.csv (VLM-based discriminability)
    results/lang_sweep_logs/reconstruct.csv      (attack F1 / cos_sim per condition)

Outputs:
    paper/figures/lang_sweep.tex                 (TikZ scatter: delta vs loss ratio, colored by domain/class)
    paper/tables/lang_sweep.tex                  (LaTeX table: per-query metrics)
    results/lang_sweep_logs/summary.csv          (merged data, for inspection)
"""
import csv
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "prototype"))
from language_sweep_config import LANGUAGE_SWEEP_QUERIES  # noqa: E402

LOG_DIR = ROOT / "results" / "lang_sweep_logs"
PAPER_DIR = ROOT / "paper"
SUMMARY_CSV = LOG_DIR / "summary.csv"
FIGURE_TEX = PAPER_DIR / "figures" / "lang_sweep.tex"
TABLE_TEX = PAPER_DIR / "tables" / "lang_sweep.tex"


def read_csv(path):
    if not path.exists():
        return []
    with open(path) as f:
        return list(csv.DictReader(f))


def aggregate_recon(rows):
    """Aggregate attack F1 over seeds per (domain, tag, condition)."""
    bucket = {}
    for r in rows:
        if not r.get("f1"):
            continue
        key = (r["domain"], r["tag"], r["condition"])
        bucket.setdefault(key, []).append(float(r["f1"]))
    agg = {}
    for k, vals in bucket.items():
        n = len(vals)
        mean = sum(vals) / n
        var = sum((v - mean) ** 2 for v in vals) / n if n > 1 else 0.0
        std = var ** 0.5
        agg[k] = {"mean": mean, "std": std, "n": n}
    return agg


def build_summary():
    manifest = {r["tag"]: r for r in read_csv(LOG_DIR / "manifest.csv") if r.get("ok") == "True"}
    discrim = {r["tag"]: r for r in read_csv(LOG_DIR / "discriminability.csv")}
    recon = aggregate_recon(read_csv(LOG_DIR / "reconstruct.csv"))

    rows = []
    for domain, queries in LANGUAGE_SWEEP_QUERIES.items():
        for tag, text, cls in queries:
            m = manifest.get(tag, {})
            d = discrim.get(tag, {})
            clean = recon.get((domain, tag, "clean"), {})
            nbfu = recon.get((domain, tag, "nbfu"), {})
            rows.append({
                "domain": domain, "tag": tag, "class": cls, "text": text,
                "loss_ratio": float(m.get("loss_ratio", "nan") or "nan"),
                "delta": float(d.get("delta", "nan") or "nan"),
                "clean_f1_mean": clean.get("mean"),
                "clean_f1_std": clean.get("std"),
                "clean_n_seeds": clean.get("n", 0),
                "nbfu_f1_mean": nbfu.get("mean"),
                "nbfu_f1_std": nbfu.get("std"),
                "nbfu_n_seeds": nbfu.get("n", 0),
            })

    with open(SUMMARY_CSV, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        for r in rows:
            w.writerow(r)
    print(f"Wrote {len(rows)} rows to {SUMMARY_CSV}")
    return rows


def emit_table(rows):
    TABLE_TEX.parent.mkdir(parents=True, exist_ok=True)
    lines = []
    lines.append("% AUTO-GENERATED by prototype/analyze_language_sweep.py")
    lines.append("\\begin{table*}[t]")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append("\\setlength{\\tabcolsep}{4pt}")
    lines.append("\\begin{tabular}{llrrrr}")
    lines.append("\\toprule")
    lines.append("Tag & Class & Loss ratio $R$ & Discrim. $\\Delta$ & Clean F1 & NBFU $\\varepsilon{=}5$ F1 \\\\")
    lines.append("\\midrule")
    cur_domain = None
    for r in rows:
        if r["domain"] != cur_domain:
            if cur_domain is not None:
                lines.append("\\midrule")
            label = "Medical (BiomedCLIP)" if r["domain"] == "medical" else "UAV (CLIP)"
            lines.append(f"\\multicolumn{{6}}{{l}}{{\\textit{{{label}}}}} \\\\")
            cur_domain = r["domain"]
        R = r["loss_ratio"]
        d = r["delta"]
        cf = r["clean_f1_mean"]
        nf = r["nbfu_f1_mean"]
        cf_s = f"{cf:.3f}$\\pm$.{int(round((r['clean_f1_std'] or 0)*100)):02d}" if cf is not None else "--"
        nf_s = f"{nf:.3f}$\\pm$.{int(round((r['nbfu_f1_std'] or 0)*100)):02d}" if nf is not None else "--"
        R_s = f"{R:.2f}" if R == R else "--"
        d_s = f"{d:.3f}" if d == d else "--"
        tag_disp = r["tag"].replace("_", r"\_")
        lines.append(f"{tag_disp} & {r['class']} & {R_s} & {d_s} & {cf_s} & {nf_s} \\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append(
        "\\caption{Language sweep across 24 queries (12 medical + 12 UAV). Loss ratio $R$ is the post-training "
        "amplification factor; discriminability $\\Delta$ is the top-10\\%--bottom-10\\% cosine-similarity margin "
        "of the VLM text embedding against the auxiliary image set. Clean F1 and NBFU $\\varepsilon{=}5$ F1 are mean "
        "attack F1 (HF-GradInv, 24k iterations) over 3 seeds (42, 123, 256). On UAV, NBFU drives F1 to $\\le$0.13 "
        "across all 12 queries (mean 0.06); on medical, defense margins vary from $+88\\%$ to $-113\\%$ per query, "
        "indicating that defense robustness depends on query phrasing in the visually-similar domain.}")
    lines.append("\\label{tab:langsweep}")
    lines.append("\\end{table*}")
    TABLE_TEX.write_text("\n".join(lines))
    print(f"Wrote {TABLE_TEX}")


def emit_figure(rows):
    FIGURE_TEX.parent.mkdir(parents=True, exist_ok=True)
    domain_color = {"medical": "blue", "uav": "red"}
    class_mark = {"paraphrase": "o", "composition": "square*", "negation": "triangle*", "diversity": "diamond*"}

    lines = []
    lines.append("% AUTO-GENERATED by prototype/analyze_language_sweep.py")
    lines.append("\\begin{tikzpicture}")
    lines.append(
        "\\begin{axis}[")
    lines.append("  width=\\columnwidth, height=6.5cm,")
    lines.append("  xlabel={Discriminability $\\Delta$ (top-10\\% minus bot-10\\% cos)}, ylabel={Loss ratio $R$ (log)},")
    lines.append("  grid=major, grid style={gray!20}, axis lines=left,")
    lines.append("  legend pos=south east, legend style={font=\\tiny, fill=white, fill opacity=0.85, draw opacity=1, text opacity=1},")
    lines.append("  legend columns=2,")
    lines.append("  ymode=log, ymin=1, ymax=300,")
    lines.append("]")

    # one plot command per (domain, class) combination so legend is informative
    seen = {}
    for r in rows:
        if r["loss_ratio"] != r["loss_ratio"] or r["delta"] != r["delta"]:
            continue
        key = (r["domain"], r["class"])
        seen.setdefault(key, []).append((r["delta"], r["loss_ratio"], r["tag"]))

    for (domain, cls), pts in seen.items():
        color = domain_color[domain]
        mark = class_mark[cls]
        opts = f"color={color}, mark={mark}, only marks, mark size=2pt"
        lines.append(f"\\addplot[{opts}] coordinates {{")
        for d, R, _ in pts:
            lines.append(f"  ({d:.4f}, {R:.2f})")
        lines.append("};")
        lines.append(f"\\addlegendentry{{{domain[:3].title()} {cls}}}")

    lines.append("\\end{axis}")
    lines.append("\\end{tikzpicture}")
    FIGURE_TEX.write_text("\n".join(lines))
    print(f"Wrote {FIGURE_TEX}")


def main():
    rows = build_summary()
    emit_table(rows)
    emit_figure(rows)


if __name__ == "__main__":
    main()
